# Generated by Django 4.0.2 on 2023-09-15 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_location_email_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_delete',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='modify_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
