# Generated by Django 4.0.2 on 2023-04-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_delete', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, default='No Name', help_text='Customer name', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='ex@2xample.com', help_text='Customer email', max_length=50)),
                ('phone', models.CharField(blank=True, default='09122222222', help_text='Customer phone number', max_length=16)),
                ('password', models.CharField(blank=True, default='111', help_text='Customer password', max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_delete', models.BooleanField(default=False, editable=False)),
                ('country', models.CharField(default='Country', help_text='Country name', max_length=50)),
                ('city', models.CharField(default='City', help_text='City name', max_length=50)),
                ('street', models.CharField(default='Address', help_text='Full Address', max_length=200)),
                ('zipcode', models.CharField(blank=True, default='1111111111', help_text='Zip Code', max_length=11, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
