# Generated by Django 4.0.2 on 2023-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='brand/'),
        ),
    ]
