# Generated by Django 4.0.2 on 2023-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('check', 'Check Out'), ('paid', 'Paid'), ('failed', 'Failed')], default='new', help_text='Status Options', max_length=10),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
